name: Publish package to the Github Repository

on:
  push:
    branches:
      - master
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven
          server-id: ossrh

      - name: DryRun Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          dry_run: true

      - name: Update pom.xml
        if: steps.semantic.outputs.new_release_published == 'true'
        run: mvn versions:set -DnewVersion=${{ steps.semantic.outputs.new_release_version }} -DprocessAllModules -DgenerateBackupPoms=false

      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v5.0.0
        with:
          gpg_private_key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: Publish java package
        run: mvn --batch-mode deploy -Dmaven.test.skip
      - name: Release with Maven
        run: |
          mvn -B -U \
            -Pci-cd \
            -X \
            release:prepare \
            release:perform \
            source:jar \
            -s settings.xml \
            -Dgpg.passphrase=${{ secrets.MAVEN_GPG_PASSPHRASE }} \
            -DreleaseVersion=${{ steps.semantic.outputs.new_release_version }} \
            deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
